-- Table definition for `shift_data.intervention_catalog` using CTE + UNNEST
-- This is the canonical source of truth for intervention catalog data
-- Managed as Infrastructure as Code via Terraform

CREATE OR REPLACE TABLE `shift_data.intervention_catalog` AS
WITH nudges AS (
  SELECT * FROM UNNEST([
    STRUCT(
      'stress_high_mind_001' AS intervention_key,
      'stress' AS metric,
      'high' AS level,
      'low' AS target_level,
      'mind' AS nudge_type,
      'Active Balance' AS persona,
      'notification_banner' AS surface,
      'Stress / High / Mind' AS title,
      'You are carrying too much right now. Step away, close your eyes, and remind yourself: This moment will pass. Let your breath lead you back.' AS body,
      TRUE AS enabled
    ),
    STRUCT(
      'stress_high_mind_002' AS intervention_key,
      'stress' AS metric,
      'high' AS level,
      'low' AS target_level,
      'mind' AS nudge_type,
      NULL AS persona,
      'notification_banner' AS surface,
      'Stress / High / Mind' AS title,
      'Remember, not everything is urgent. Your wellness is, though. Step away, breathe, and let your mind reset before re-entering.' AS body,
      TRUE AS enabled
    ),
    STRUCT(
      'stress_high_body_003' AS intervention_key,
      'stress' AS metric,
      'high' AS level,
      'low' AS target_level,
      'body' AS nudge_type,
      NULL AS persona,
      'notification_banner' AS surface,
      'Stress / High / Body' AS title,
      'Find a quiet corner. Place your hand over your heart, take 5 deep belly breaths, and feel your body slow everything down.' AS body,
      TRUE AS enabled
    ),
    STRUCT(
      'stress_high_body_004' AS intervention_key,
      'stress' AS metric,
      'high' AS level,
      'low' AS target_level,
      'body' AS nudge_type,
      NULL AS persona,
      'notification_banner' AS surface,
      'Stress / High / Body' AS title,
      'Your nervous system needs grounding. 3 deep breaths can completely reset your system. Sit or stand tall, press your feet into the floor, and feel your 3 breaths anchor you.' AS body,
      TRUE AS enabled
    ),
    STRUCT(
      'stress_high_belly_005' AS intervention_key,
      'stress' AS metric,
      'high' AS level,
      'low' AS target_level,
      'belly' AS nudge_type,
      NULL AS persona,
      'notification_banner' AS surface,
      'Stress / High / Belly' AS title,
      'Skip the sugar hit — your gut needs grounding. Try something warm and steady: herbal tea, broth, or a meal with protein and healthy fats.' AS body,
      TRUE AS enabled
    ),
    STRUCT(
      'stress_high_belly_006' AS intervention_key,
      'stress' AS metric,
      'high' AS level,
      'low' AS target_level,
      'belly' AS nudge_type,
      NULL AS persona,
      'notification_banner' AS surface,
      'Stress / High / Belly' AS title,
      'Your gut is talking. Skip the quick fix and soothe your system with something warm — soup, tea, or oats with cinnamon.' AS body,
      TRUE AS enabled
    ),
    STRUCT(
      'stress_medium_mind_007' AS intervention_key,
      'stress' AS metric,
      'medium' AS level,
      'low' AS target_level,
      'mind' AS nudge_type,
      NULL AS persona,
      'notification_banner' AS surface,
      'Stress / Medium / Mind' AS title,
      'Pause for 60 seconds. Inhale calm, exhale tension. Your next move will feel clearer after that.' AS body,
      TRUE AS enabled
    ),
    STRUCT(
      'stress_medium_mind_008' AS intervention_key,
      'stress' AS metric,
      'medium' AS level,
      'low' AS target_level,
      'mind' AS nudge_type,
      NULL AS persona,
      'notification_banner' AS surface,
      'Stress / Medium / Mind' AS title,
      'Your thoughts are racing — slow them with presence. What is one thing you can control right now?' AS body,
      TRUE AS enabled
    ),
    STRUCT(
      'stress_medium_body_009' AS intervention_key,
      'stress' AS metric,
      'medium' AS level,
      'low' AS target_level,
      'body' AS nudge_type,
      NULL AS persona,
      'notification_banner' AS surface,
      'Stress / Medium / Body' AS title,
      'Stand up and stretch your arms overhead. Move your spine. Release the physical weight of your thoughts.' AS body,
      TRUE AS enabled
    ),
    STRUCT(
      'stress_medium_body_010' AS intervention_key,
      'stress' AS metric,
      'medium' AS level,
      'low' AS target_level,
      'body' AS nudge_type,
      NULL AS persona,
      'notification_banner' AS surface,
      'Stress / Medium / Body' AS title,
      'Stretch your spine, roll your neck, open your chest. Let your body remind your brain that you are safe.' AS body,
      TRUE AS enabled
    ),
    STRUCT(
      'stress_medium_belly_011' AS intervention_key,
      'stress' AS metric,
      'medium' AS level,
      'low' AS target_level,
      'belly' AS nudge_type,
      NULL AS persona,
      'notification_banner' AS surface,
      'Stress / Medium / Belly' AS title,
      'Stress burns through key nutrients. Reach for magnesium-rich foods like dark chocolate, greens, or avocado to help your body reset.' AS body,
      TRUE AS enabled
    ),
    STRUCT(
      'stress_medium_belly_012' AS intervention_key,
      'stress' AS metric,
      'medium' AS level,
      'low' AS target_level,
      'belly' AS nudge_type,
      NULL AS persona,
      'notification_banner' AS surface,
      'Stress / Medium / Belly' AS title,
      'Stress drains minerals. Add something rich in magnesium or potassium — a banana, dark chocolate, or leafy greens.' AS body,
      TRUE AS enabled
    ),
    STRUCT(
      'stress_low_mind_013' AS intervention_key,
      'stress' AS metric,
      'low' AS level,
      'low' AS target_level,
      'mind' AS nudge_type,
      NULL AS persona,
      'notification_banner' AS surface,
      'Stress / Low / Mind' AS title,
      'Take a slow breath. You have got this — one thing at a time.' AS body,
      TRUE AS enabled
    ),
    STRUCT(
      'stress_low_mind_014' AS intervention_key,
      'stress' AS metric,
      'low' AS level,
      'low' AS target_level,
      'mind' AS nudge_type,
      NULL AS persona,
      'notification_banner' AS surface,
      'Stress / Low / Mind' AS title,
      'Breathe before you react. A single deep inhale can shift your whole perspective.' AS body,
      TRUE AS enabled
    ),
    STRUCT(
      'stress_low_body_015' AS intervention_key,
      'stress' AS metric,
      'low' AS level,
      'low' AS target_level,
      'body' AS nudge_type,
      NULL AS persona,
      'notification_banner' AS surface,
      'Stress / Low / Body' AS title,
      'Unclench your jaw. Drop your shoulders. Let your body catch up to your breath.' AS body,
      TRUE AS enabled
    ),
    STRUCT(
      'stress_low_body_016' AS intervention_key,
      'stress' AS metric,
      'low' AS level,
      'low' AS target_level,
      'body' AS nudge_type,
      NULL AS persona,
      'notification_banner' AS surface,
      'Stress / Low / Body' AS title,
      'Do a quick body scan — where is the tension living? Exhale into that spot and release it.' AS body,
      TRUE AS enabled
    ),
    STRUCT(
      'stress_low_belly_017' AS intervention_key,
      'stress' AS metric,
      'low' AS level,
      'low' AS target_level,
      'belly' AS nudge_type,
      NULL AS persona,
      'notification_banner' AS surface,
      'Stress / Low / Belly' AS title,
      'Sip some water. Your gut and mind are in this together.' AS body,
      TRUE AS enabled
    ),
    STRUCT(
      'stress_low_belly_018' AS intervention_key,
      'stress' AS metric,
      'low' AS level,
      'low' AS target_level,
      'belly' AS nudge_type,
      NULL AS persona,
      'notification_banner' AS surface,
      'Stress / Low / Belly' AS title,
      'Add something nourishing — a handful of nuts or fruit. Small bites of balance calm your system.' AS body,
      TRUE AS enabled
    ),
    STRUCT(
      'fatigue_high_mind_019' AS intervention_key,
      'fatigue' AS metric,
      'high' AS level,
      'low' AS target_level,
      'mind' AS nudge_type,
      NULL AS persona,
      'notification_banner' AS surface,
      'Fatigue / High / Mind' AS title,
      'You are out of focus because you are out of fuel. Rest your mind — even 10 minutes offline can recharge you.' AS body,
      TRUE AS enabled
    ),
    STRUCT(
      'fatigue_high_mind_020' AS intervention_key,
      'fatigue' AS metric,
      'high' AS level,
      'low' AS target_level,
      'mind' AS nudge_type,
      NULL AS persona,
      'notification_banner' AS surface,
      'Fatigue / High / Mind' AS title,
      'Your focus is fading because your tank is empty. Rest is not laziness — it is fuel for clarity.' AS body,
      TRUE AS enabled
    ),
    STRUCT(
      'fatigue_high_body_021' AS intervention_key,
      'fatigue' AS metric,
      'high' AS level,
      'low' AS target_level,
      'body' AS nudge_type,
      NULL AS persona,
      'notification_banner' AS surface,
      'Fatigue / High / Body' AS title,
      'Your body is whispering: enough for now. Stretch, close your eyes, or take a real rest. Energy follows recovery.' AS body,
      TRUE AS enabled
    ),
    STRUCT(
      'fatigue_high_body_022' AS intervention_key,
      'fatigue' AS metric,
      'high' AS level,
      'low' AS target_level,
      'body' AS nudge_type,
      NULL AS persona,
      'notification_banner' AS surface,
      'Fatigue / High / Body' AS title,
      'Your body is asking for a break, not more caffeine. Close your eyes, lay down if you can, and breathe into stillness.' AS body,
      TRUE AS enabled
    ),
    STRUCT(
      'fatigue_high_belly_023' AS intervention_key,
      'fatigue' AS metric,
      'high' AS level,
      'low' AS target_level,
      'belly' AS nudge_type,
      NULL AS persona,
      'notification_banner' AS surface,
      'Fatigue / High / Belly' AS title,
      'If you are crashing, your blood sugar might be too. Choose something nourishing and slow-burning — think lean protein, greens, and healthy fats.' AS body,
      TRUE AS enabled
    ),
    STRUCT(
      'fatigue_high_belly_024' AS intervention_key,
      'fatigue' AS metric,
      'high' AS level,
      'low' AS target_level,
      'belly' AS nudge_type,
      NULL AS persona,
      'notification_banner' AS surface,
      'Fatigue / High / Belly' AS title,
      'If you are drained, eat something that rebuilds — lentils, salmon, greens, or quinoa. Your cells are asking to be refueled.' AS body,
      TRUE AS enabled
    ),
    STRUCT(
      'fatigue_medium_mind_025' AS intervention_key,
      'fatigue' AS metric,
      'medium' AS level,
      'low' AS target_level,
      'mind' AS nudge_type,
      NULL AS persona,
      'notification_banner' AS surface,
      'Fatigue / Medium / Mind' AS title,
      'Mental fog is not failure — it is feedback. Give your mind a pause, even 2 quiet minutes.' AS body,
      TRUE AS enabled
    ),
    STRUCT(
      'fatigue_medium_mind_026' AS intervention_key,
      'fatigue' AS metric,
      'medium' AS level,
      'low' AS target_level,
      'mind' AS nudge_type,
      NULL AS persona,
      'notification_banner' AS surface,
      'Fatigue / Medium / Mind' AS title,
      'Feeling foggy? Step outside for fresh air. A few minutes of natural light wakes up your mental energy.' AS body,
      TRUE AS enabled
    ),
    STRUCT(
      'fatigue_medium_body_027' AS intervention_key,
      'fatigue' AS metric,
      'medium' AS level,
      'low' AS target_level,
      'body' AS nudge_type,
      NULL AS persona,
      'notification_banner' AS surface,
      'Fatigue / Medium / Body' AS title,
      'Take a 5-minute walk, even if it is inside. Movement recharges your blood flow and your brain.' AS body,
      TRUE AS enabled
    ),
    STRUCT(
      'fatigue_medium_body_028' AS intervention_key,
      'fatigue' AS metric,
      'medium' AS level,
      'low' AS target_level,
      'body' AS nudge_type,
      NULL AS persona,
      'notification_banner' AS surface,
      'Fatigue / Medium / Body' AS title,
      'Step outside for fresh air. A few minutes of natural light wakes up your mental energy.' AS body,
      TRUE AS enabled
    ),
    STRUCT(
      'fatigue_medium_belly_029' AS intervention_key,
      'fatigue' AS metric,
      'medium' AS level,
      'low' AS target_level,
      'belly' AS nudge_type,
      NULL AS persona,
      'notification_banner' AS surface,
      'Fatigue / Medium / Belly' AS title,
      'Your body may need steady fuel. Eat something with protein and complex carbs — like eggs, hummus, or oats — to bring your energy back.' AS body,
      TRUE AS enabled
    ),
    STRUCT(
      'fatigue_medium_belly_030' AS intervention_key,
      'fatigue' AS metric,
      'medium' AS level,
      'low' AS target_level,
      'belly' AS nudge_type,
      NULL AS persona,
      'notification_banner' AS surface,
      'Fatigue / Medium / Belly' AS title,
      'Reach for balance: a mix of protein, fiber, and healthy fat — think apple + nut butter or eggs + avocado.' AS body,
      TRUE AS enabled
    ),
    STRUCT(
      'fatigue_low_mind_031' AS intervention_key,
      'fatigue' AS metric,
      'low' AS level,
      'low' AS target_level,
      'mind' AS nudge_type,
      NULL AS persona,
      'notification_banner' AS surface,
      'Fatigue / Low / Mind' AS title,
      'Your body is asking for a micro break. Look away from the screen and take 3 conscious breaths.' AS body,
      TRUE AS enabled
    ),
    STRUCT(
      'fatigue_low_mind_032' AS intervention_key,
      'fatigue' AS metric,
      'low' AS level,
      'low' AS target_level,
      'mind' AS nudge_type,
      NULL AS persona,
      'notification_banner' AS surface,
      'Fatigue / Low / Mind' AS title,
      'Mental reset time: look up from your screen, take a few deep breaths, and let your brain breathe too.' AS body,
      TRUE AS enabled
    ),
    STRUCT(
      'fatigue_low_body_033' AS intervention_key,
      'fatigue' AS metric,
      'low' AS level,
      'low' AS target_level,
      'body' AS nudge_type,
      NULL AS persona,
      'notification_banner' AS surface,
      'Fatigue / Low / Body' AS title,
      'Roll your shoulders. Stand tall. A minute of movement beats another cup of coffee.' AS body,
      TRUE AS enabled
    ),
    STRUCT(
      'fatigue_low_body_034' AS intervention_key,
      'fatigue' AS metric,
      'low' AS level,
      'low' AS target_level,
      'body' AS nudge_type,
      NULL AS persona,
      'notification_banner' AS surface,
      'Fatigue / Low / Body' AS title,
      'Move your body gently — stand, stretch, roll your wrists. Small motion creates real energy.' AS body,
      TRUE AS enabled
    ),
    STRUCT(
      'fatigue_low_belly_035' AS intervention_key,
      'fatigue' AS metric,
      'low' AS level,
      'low' AS target_level,
      'belly' AS nudge_type,
      NULL AS persona,
      'notification_banner' AS surface,
      'Fatigue / Low / Belly' AS title,
      'Check your hydration — sometimes tired just means thirsty. Sip some water or add electrolytes.' AS body,
      TRUE AS enabled
    ),
    STRUCT(
      'fatigue_low_belly_036' AS intervention_key,
      'fatigue' AS metric,
      'low' AS level,
      'low' AS target_level,
      'belly' AS nudge_type,
      NULL AS persona,
      'notification_banner' AS surface,
      'Fatigue / Low / Belly' AS title,
      'Start with hydration — your energy might just be low water. Add a pinch of sea salt or lemon for extra support.' AS body,
      TRUE AS enabled
    ),
    STRUCT(
      'mood_high_mind_037' AS intervention_key,
      'mood' AS metric,
      'high' AS level,
      'medium' AS target_level,
      'mind' AS nudge_type,
      NULL AS persona,
      'notification_banner' AS surface,
      'Mood / High / Mind' AS title,
      'Big emotions are powerful. Ground your excitement with a deep breath before deciding what is next.' AS body,
      TRUE AS enabled
    ),
    STRUCT(
      'mood_high_mind_038' AS intervention_key,
      'mood' AS metric,
      'high' AS level,
      'medium' AS target_level,
      'mind' AS nudge_type,
      NULL AS persona,
      'notification_banner' AS surface,
      'Mood / High / Mind' AS title,
      'When energy spikes, your prefrontal cortex can lag behind. Slow breathing or journaling helps balance excitement with clarity.' AS body,
      TRUE AS enabled
    ),
    STRUCT(
      'mood_high_body_039' AS intervention_key,
      'mood' AS metric,
      'high' AS level,
      'medium' AS target_level,
      'body' AS nudge_type,
      NULL AS persona,
      'notification_banner' AS surface,
      'Mood / High / Body' AS title,
      'When energy spikes, slow your pace. Exhale longer than you inhale — it tells your body you are safe to soften.' AS body,
      TRUE AS enabled
    ),
    STRUCT(
      'mood_high_body_040' AS intervention_key,
      'mood' AS metric,
      'high' AS level,
      'medium' AS target_level,
      'body' AS nudge_type,
      NULL AS persona,
      'notification_banner' AS surface,
      'Mood / High / Body' AS title,
      'Feeling wired? Your heart rate might be elevated. Try a slow exhale twice as long as your inhale to bring your body back to balance.' AS body,
      TRUE AS enabled
    ),
    STRUCT(
      'mood_high_belly_041' AS intervention_key,
      'mood' AS metric,
      'high' AS level,
      'medium' AS target_level,
      'belly' AS nudge_type,
      NULL AS persona,
      'notification_banner' AS surface,
      'Mood / High / Belly' AS title,
      'Excitement burns energy fast. Ground yourself with something hearty — oats, nuts, or a balanced meal.' AS body,
      TRUE AS enabled
    ),
    STRUCT(
      'mood_high_belly_042' AS intervention_key,
      'mood' AS metric,
      'high' AS level,
      'medium' AS target_level,
      'belly' AS nudge_type,
      NULL AS persona,
      'notification_banner' AS surface,
      'Mood / High / Belly' AS title,
      'High emotional energy can burn through magnesium and B-vitamins. Replenish with dark leafy greens, nuts, and seeds.' AS body,
      TRUE AS enabled
    ),
    STRUCT(
      'mood_medium_mind_043' AS intervention_key,
      'mood' AS metric,
      'medium' AS level,
      'low' AS target_level,
      'mind' AS nudge_type,
      NULL AS persona,
      'notification_banner' AS surface,
      'Mood / Medium / Mind' AS title,
      'Notice what is weighing on your mind — name it, then breathe through it. Awareness brings power back to you.' AS body,
      TRUE AS enabled
    ),
    STRUCT(
      'mood_medium_mind_044' AS intervention_key,
      'mood' AS metric,
      'medium' AS level,
      'low' AS target_level,
      'mind' AS nudge_type,
      NULL AS persona,
      'notification_banner' AS surface,
      'Mood / Medium / Mind' AS title,
      'Ruminating thoughts keep your mood stuck. Try labeling what you feel — naming emotions activates logic and reduces intensity.' AS body,
      TRUE AS enabled
    ),
    STRUCT(
      'mood_medium_body_045' AS intervention_key,
      'mood' AS metric,
      'medium' AS level,
      'low' AS target_level,
      'body' AS nudge_type,
      NULL AS persona,
      'notification_banner' AS surface,
      'Mood / Medium / Body' AS title,
      'Your body stores emotion. Shake out your arms, roll your shoulders, or take a brisk walk to move energy through.' AS body,
      TRUE AS enabled
    ),
    STRUCT(
      'mood_medium_body_046' AS intervention_key,
      'mood' AS metric,
      'medium' AS level,
      'low' AS target_level,
      'body' AS nudge_type,
      NULL AS persona,
      'notification_banner' AS surface,
      'Mood / Medium / Body' AS title,
      'Posture affects mood. Stand tall, roll your shoulders back — this opens your chest and signals confidence to your nervous system.' AS body,
      TRUE AS enabled
    ),
    STRUCT(
      'mood_medium_belly_047' AS intervention_key,
      'mood' AS metric,
      'medium' AS level,
      'low' AS target_level,
      'belly' AS nudge_type,
      NULL AS persona,
      'notification_banner' AS surface,
      'Mood / Medium / Belly' AS title,
      'Stable blood sugar = stable mood. Go for slow-burning fuel — protein and complex carbs, not just caffeine or sweets.' AS body,
      TRUE AS enabled
    ),
    STRUCT(
      'mood_medium_belly_048' AS intervention_key,
      'mood' AS metric,
      'medium' AS level,
      'low' AS target_level,
      'belly' AS nudge_type,
      NULL AS persona,
      'notification_banner' AS surface,
      'Mood / Medium / Belly' AS title,
      'Your gut makes most of your serotonin. Support it with fiber-rich foods — greens, legumes, whole grains — to keep your mood steady.' AS body,
      TRUE AS enabled
    ),
    STRUCT(
      'mood_low_mind_049' AS intervention_key,
      'mood' AS metric,
      'low' AS level,
      'low' AS target_level,
      'mind' AS nudge_type,
      NULL AS persona,
      'notification_banner' AS surface,
      'Mood / Low / Mind' AS title,
      'You do not have to feel amazing to move forward. One small action can lift your energy.' AS body,
      TRUE AS enabled
    ),
    STRUCT(
      'mood_low_mind_050' AS intervention_key,
      'mood' AS metric,
      'low' AS level,
      'low' AS target_level,
      'mind' AS nudge_type,
      NULL AS persona,
      'notification_banner' AS surface,
      'Mood / Low / Mind' AS title,
      'When mood dips, your brain is serotonin may be running low. A short walk or sunlight boosts serotonin naturally — give your mind that spark.' AS body,
      TRUE AS enabled
    ),
    STRUCT(
      'mood_low_body_051' AS intervention_key,
      'mood' AS metric,
      'low' AS level,
      'low' AS target_level,
      'body' AS nudge_type,
      NULL AS persona,
      'notification_banner' AS surface,
      'Mood / Low / Body' AS title,
      'Move something — your body shifts your chemistry. Even 2 minutes of stretching can change your headspace.' AS body,
      TRUE AS enabled
    ),
    STRUCT(
      'mood_low_body_052' AS intervention_key,
      'mood' AS metric,
      'low' AS level,
      'low' AS target_level,
      'body' AS nudge_type,
      NULL AS persona,
      'notification_banner' AS surface,
      'Mood / Low / Body' AS title,
      'Movement releases endorphins — your body is built-in mood lifters. Even 5 minutes of walking can raise dopamine and shift your state.' AS body,
      TRUE AS enabled
    ),
    STRUCT(
      'mood_low_belly_053' AS intervention_key,
      'mood' AS metric,
      'low' AS level,
      'low' AS target_level,
      'belly' AS nudge_type,
      NULL AS persona,
      'notification_banner' AS surface,
      'Mood / Low / Belly' AS title,
      'Add something colorful to your plate — berries, greens, or citrus. Mood and micronutrients go hand in hand.' AS body,
      TRUE AS enabled
    ),
    STRUCT(
      'mood_low_belly_054' AS intervention_key,
      'mood' AS metric,
      'low' AS level,
      'low' AS target_level,
      'belly' AS nudge_type,
      NULL AS persona,
      'notification_banner' AS surface,
      'Mood / Low / Belly' AS title,
      'Low mood often links to low blood sugar. Eat something with steady carbs + protein — like oats with nut butter or Greek yogurt with fruit.' AS body,
      TRUE AS enabled
    )
  ])
)
SELECT
  intervention_key,
  metric,
  level,
  target_level,
  nudge_type,
  persona,
  surface,
  title,
  body,
  enabled
FROM nudges;









